builds:
  -
    main: ./main.go
    binary: giter
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - netbsd
      - openbsd
    goarch:
      - amd64
      - 386
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: jsmartx
    name: homebrew-giter
  folder: Formula
  homepage:  https://github.com/jsmartx/
  description: Git users manager
  test: |
    system "#{bin}/giter -v"
